/**
 * @author saiteja 
 * @version 1.1
 */

package com.lti.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.lti.idgen.IdGenerator;

/* This class represents an entity for Claim */

@Entity
@Table(name = "claim_details")
public class Claim {
	@Id
	@Column(name = "claim_id")
	@GeneratedValue(generator = "claimseq", strategy = GenerationType.SEQUENCE)
	@GenericGenerator(name = "claimseq", strategy = "com.lti.idgen.IdGenerator", parameters = {
			@Parameter(name = IdGenerator.INCREMENT_PARAM, value = "50"),
			@Parameter(name = IdGenerator.VALUE_PREFIX_PARAMETER, value = "CL_"),
			@Parameter(name = IdGenerator.NUMBER_FORMAT_PARAMETER, value = "%05d")

	})
	private String claimId; // stores claim id, primary key, is autogenerated

	private double amount; // stores claim amount

	@Column(length = 20)
	private String status; // stores claim status

	@Column(length = 20)
	private String claimDate; // stores claiming date

	@Column(length = 50)
	private String reason; // stores claim reason

	@Column(length = 32)
	private String accountno; // stores account no

	@Column(length = 200)
	private String vehicleimage; // stores vehicle image path
	
	//Getters and Setters

	public String getVehicleimage() {
		return vehicleimage;
	}

	public void setVehicleimage(String vehicleimage) {
		this.vehicleimage = vehicleimage;
	}

	public String getAccountno() {
		return accountno;
	}

	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	public String getClaimId() {
		return claimId;
	}

	public void setClaimId(String cid) {
		this.claimId = cid;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getClaimDate() {
		return claimDate;
	}

	public void setClaimDate(String claimDate) {
		this.claimDate = claimDate;
	}
}
